version: '3.4'

services:
  datamonitoring.worker:
    image: ${DOCKER_REGISTRY-}datamonitoringworker
    build:
      context: .
      dockerfile: src/DataMonitoring.Worker/Dockerfile

  mongo:
    image: mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081